package de.innologic.auth.web.error;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Application-wide error codes.")
public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    TOKEN_INVALID,
    TOKEN_EXPIRED,
    TOTP_INVALID,
    SOCIAL_AUTH_FAILED,
    EMAIL_NOT_VERIFIED,
    MFA_NOT_ENROLLED,
    MFA_REQUIRED,
    TENANT_MISMATCH,
    SCOPE_MISSING,
    ACCESS_DENIED,
    RATE_LIMITED,
    IDEMPOTENCY_CONFLICT,
    DUPLICATE_EMAIL,
    SOCIAL_IDENTITY_ALREADY_LINKED,
    EMAIL_ALREADY_USED_BY_OTHER_PROVIDER,
    REGISTRATION_NOT_FOUND,
    REGISTRATION_EXPIRED,
    DOWNSTREAM_USER_UNAVAILABLE,
    DOWNSTREAM_COMPANY_UNAVAILABLE,
    DOWNSTREAM_IAM_UNAVAILABLE,
    SOCIAL_PROVIDER_UNAVAILABLE,
    REFRESH_INVALID,
    SESSION_REVOKED,
    SESSION_EXPIRED,
    INTERNAL_API_KEY_INVALID,
    INTERNAL_ERROR
}
