spring.application.name=auth-service
server.port=${AUTHPORT:8080}

server.servlet.context-path=/api/v1/auth

spring.datasource.url=jdbc:mariadb://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:3306}/${AUTH_DB_NAME:auth}
spring.datasource.username=${AUTH_DB_USER:root}
spring.datasource.password=${AUTH_DB_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
