spring.datasource.url=jdbc:mariadb://${AUTH_DB_HOST:mariadb}:${AUTH_DB_PORT:3306}/${AUTH_DB_NAME:auth}
spring.datasource.username=${AUTH_DB_USER:root}
spring.datasource.password=${AUTH_DB_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

server.port=${AUTH_SERVER_PORT:8080}
management.server.port=${AUTH_MANAGEMENT_SERVER_PORT:8201}
server.servlet.context-path=${AUTH_CONTEXT_PATH:/api/v1}
management.endpoints.web.base-path=${AUTH_ACTUATOR_BASE_PATH:/actuator}
